# Generated by Django 5.1.3 on 2024-11-13 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=30)),
                ("text", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("To do", "To Do"),
                            ("In action", "In Action"),
                            ("Done", "Done"),
                        ],
                        default="To do",
                        max_length=10,
                    ),
                ),
                ("tags", models.TextField(blank=True, max_length=30, null=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("dead_line", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workers",
                    models.ManyToManyField(
                        related_name="foreign_tasks", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
